disturbances:
  -
    type: current
    starting_time: 25
    velocity: 3
    horizontal_angle: 0
    vertical_angle: 0
    duration: 4.9
  -
    type: current
    starting_time: 30
    velocity: 3
    horizontal_angle: 2
    vertical_angle: 0
    duration: 4.9
  -
    type: current
    starting_time: 35
    velocity: 3
    horizontal_angle: -2
    vertical_angle: 0
    duration: 4.9
  -
    type: current
    starting_time: 40
    velocity: 3
    horizontal_angle: 3
    vertical_angle: 0
    duration: 4.9
  -
    type: wrench
    starting_time: 45
    duration: 10
    force:
      - 1500
      - 0
      - -1500
    torque:
      - 3000
      - 0
      - 0


